import { DataPack } from './types';

export const INITIAL_PACKS: DataPack[] = [
  // ------------------ GP (GRAMEENPHONE) FAMILY & BUNDLE PACKS ------------------
  {
    id: 'gp-fam-1',
    title: 'GP ফ্যামেলি ৫০ জিবি + ৩০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '50 GB',
    minutes: 300,
    sms: 0,
    validity: '30 Days',
    regularPrice: 650,
    salePrice: 570,
    cashback: 20,
    isHot: true,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৫০ জিবি ইন্টারনেট + ৩০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-2',
    title: 'GP ফ্যামেলি ৬০ জিবি + ৩০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '60 GB',
    minutes: 300,
    sms: 0,
    validity: '30 Days',
    regularPrice: 700,
    salePrice: 620,
    cashback: 25,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৬০ জিবি ইন্টারনেট + ৩০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-3',
    title: 'GP ফ্যামেলি ৪০ জিবি + ৪৫০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '40 GB',
    minutes: 450,
    sms: 0,
    validity: '30 Days',
    regularPrice: 620,
    salePrice: 540,
    cashback: 20,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৪০ জিবি ইন্টারনেট + ৪৫০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-4',
    title: 'GP ফ্যামেলি ৫০ জিবি + ৫০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '50 GB',
    minutes: 500,
    sms: 0,
    validity: '30 Days',
    regularPrice: 690,
    salePrice: 610,
    cashback: 30,
    isPopular: true,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৫০ জিবি ইন্টারনেট + ৫০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-5',
    title: 'GP ফ্যামেলি ২০ জিবি + ৭০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '20 GB',
    minutes: 700,
    sms: 0,
    validity: '30 Days',
    regularPrice: 610,
    salePrice: 540,
    cashback: 20,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ২০ জিবি ইন্টারনেট + ৭০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-6',
    title: 'GP ফ্যামেলি ৩০ জিবি + ৭০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '30 GB',
    minutes: 700,
    sms: 0,
    validity: '30 Days',
    regularPrice: 650,
    salePrice: 570,
    cashback: 20,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৩০ জিবি ইন্টারনেট + ৭০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-7',
    title: 'GP ফ্যামেলি ৪০ জিবি + ৭০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '40 GB',
    minutes: 700,
    sms: 0,
    validity: '30 Days',
    regularPrice: 700,
    salePrice: 620,
    cashback: 25,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৪০ জিবি ইন্টারনেট + ৭০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-8',
    title: 'GP ফ্যামেলি ৫০ জিবি + ৭০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '50 GB',
    minutes: 700,
    sms: 0,
    validity: '30 Days',
    regularPrice: 750,
    salePrice: 670,
    cashback: 30,
    isHot: true,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৫০ জিবি ইন্টারনেট + ৭০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-9',
    title: 'GP ফ্যামেলি ২০ জিবি + ৯০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '20 GB',
    minutes: 900,
    sms: 0,
    validity: '30 Days',
    regularPrice: 650,
    salePrice: 580,
    cashback: 20,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ২০ জিবি ইন্টারনেট + ৯০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-10',
    title: 'GP ফ্যামেলি ৩০ জিবি + ৯০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '30 GB',
    minutes: 900,
    sms: 0,
    validity: '30 Days',
    regularPrice: 690,
    salePrice: 610,
    cashback: 25,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৩০ জিবি ইন্টারনেট + ৯০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-11',
    title: 'GP ফ্যামেলি ৪০ জিবি + ৯০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '40 GB',
    minutes: 900,
    sms: 0,
    validity: '30 Days',
    regularPrice: 720,
    salePrice: 640,
    cashback: 25,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৪০ জিবি ইন্টারনেট + ৯০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-12',
    title: 'GP ফ্যামেলি ৫০ জিবি + ৯০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '50 GB',
    minutes: 900,
    sms: 0,
    validity: '30 Days',
    regularPrice: 780,
    salePrice: 690,
    cashback: 30,
    isPopular: true,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৫০ জিবি ইন্টারনেট + ৯০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-13',
    title: 'GP ফ্যামেলি ৬০ জিবি + ৯০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '60 GB',
    minutes: 900,
    sms: 0,
    validity: '30 Days',
    regularPrice: 830,
    salePrice: 740,
    cashback: 35,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৬০ জিবি ইন্টারনেট + ৯০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-14',
    title: 'GP ফ্যামেলি ১০ জিবি + ১০০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '10 GB',
    minutes: 1000,
    sms: 0,
    validity: '30 Days',
    regularPrice: 630,
    salePrice: 560,
    cashback: 20,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ১০ জিবি ইন্টারনেট + ১০০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-15',
    title: 'GP ফ্যামেলি ২০ জিবি + ১০০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '20 GB',
    minutes: 1000,
    sms: 0,
    validity: '30 Days',
    regularPrice: 680,
    salePrice: 600,
    cashback: 25,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ২০ জিবি ইন্টারনেট + ১০০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-16',
    title: 'GP ফ্যামেলি ৩০ জিবি + ১০০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '30 GB',
    minutes: 1000,
    sms: 0,
    validity: '30 Days',
    regularPrice: 720,
    salePrice: 640,
    cashback: 25,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৩০ জিবি ইন্টারনেট + ১০০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-17',
    title: 'GP ফ্যামেলি ৪০ জিবি + ১০০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '40 GB',
    minutes: 1000,
    sms: 0,
    validity: '30 Days',
    regularPrice: 750,
    salePrice: 670,
    cashback: 30,
    isHot: true,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৪০ জিবি ইন্টারনেট + ১০০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-18',
    title: 'GP ফ্যামেলি ৫০ জিবি + ১০০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '50 GB',
    minutes: 1000,
    sms: 0,
    validity: '30 Days',
    regularPrice: 800,
    salePrice: 710,
    cashback: 35,
    isPopular: true,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৫০ জিবি ইন্টারনেট + ১০০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-19',
    title: 'GP ফ্যামেলি ৬০ জিবি + ১০০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '60 GB',
    minutes: 1000,
    sms: 0,
    validity: '30 Days',
    regularPrice: 850,
    salePrice: 760,
    cashback: 40,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৬০ জিবি ইন্টারনেট + ১০০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-20',
    title: 'GP ফ্যামেলি ২০ জিবি ইন্টারনেট',
    category: 'combo',
    operator: 'GP',
    data: '20 GB',
    minutes: 0,
    sms: 0,
    validity: '30 Days',
    regularPrice: 420,
    salePrice: 360,
    cashback: 15,
    description: 'গ্রামীনফোন ফ্যামেলি ২০ জিবি ৪জি স্পেশাল মেগা ডাটা প্যাক অফার।'
  },
  {
    id: 'gp-fam-21',
    title: 'GP ফ্যামেলি ৫০ জিবি ইন্টারনেট',
    category: 'combo',
    operator: 'GP',
    data: '50 GB',
    minutes: 0,
    sms: 0,
    validity: '30 Days',
    regularPrice: 580,
    salePrice: 510,
    cashback: 25,
    isHot: true,
    description: 'গ্রামীনফোন ফ্যামেলি ৫০ জিবি ৪জি স্পেশাল মেগা ডাটা প্যাক অফার।'
  },
  {
    id: 'gp-fam-22',
    title: 'GP ফ্যামেলি ৪০ জিবি ইন্টারনেট',
    category: 'combo',
    operator: 'GP',
    data: '40 GB',
    minutes: 0,
    sms: 0,
    validity: '30 Days',
    regularPrice: 520,
    salePrice: 460,
    cashback: 20,
    description: 'গ্রামীনফোন ফ্যামেলি ৪০ জিবি ৪জি স্পেশাল মেগা ডাটা প্যাক অফার।'
  },
  {
    id: 'gp-fam-23',
    title: 'GP ফ্যামেলি ২০ জিবি + ৩০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '20 GB',
    minutes: 300,
    sms: 0,
    validity: '30 Days',
    regularPrice: 480,
    salePrice: 420,
    cashback: 15,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ২০ জিবি ইন্টারনেট + ৩০০ মিনিট মেয়াদ ৩০ দিন।'
  },
  {
    id: 'gp-fam-24',
    title: 'GP ফ্যামেলি ৩৫ জিবি + ৫০০ মিনিট',
    category: 'combo',
    operator: 'GP',
    data: '35 GB',
    minutes: 500,
    sms: 0,
    validity: '30 Days',
    regularPrice: 600,
    salePrice: 530,
    cashback: 25,
    isPopular: true,
    description: 'গ্রামীনফোন ফ্যামেলি অফার ৩৫ জিবি ইন্টারনেট + ৫০০ মিনিট মেয়াদ ৩০ দিন।'
  },

  // ------------------ ROBI MINUTE PACKS ------------------
  {
    id: 'robi-min-1',
    title: 'রবি ১১০ মিনিট অফার',
    category: 'minute',
    operator: 'Robi',
    data: '0 MB',
    minutes: 110,
    sms: 0,
    validity: '30 Days',
    regularPrice: 125,
    salePrice: 110,
    cashback: 15,
    description: 'রবি ১১০ মিনিট টকটাইম অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'robi-min-2',
    title: 'রবি ১৬০ মিনিট অফার',
    category: 'minute',
    operator: 'Robi',
    data: '0 MB',
    minutes: 160,
    sms: 0,
    validity: '30 Days',
    regularPrice: 160,
    salePrice: 145,
    cashback: 15,
    description: 'রবি ১৬০ মিনিট টকটাইম অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'robi-min-3',
    title: 'রবি ২১০ মিনিট অফার',
    category: 'minute',
    operator: 'Robi',
    data: '0 MB',
    minutes: 210,
    sms: 0,
    validity: '30 Days',
    regularPrice: 195,
    salePrice: 175,
    cashback: 20,
    description: 'রবি ২১০ মিনিট টকটাইম অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'robi-min-4',
    title: 'রবি ২৬০ মিনিট অফার',
    category: 'minute',
    operator: 'Robi',
    data: '0 MB',
    minutes: 260,
    sms: 0,
    validity: '30 Days',
    regularPrice: 230,
    salePrice: 205,
    cashback: 25,
    description: 'রবি ২৬০ মিনিট টকটাইম অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'robi-min-5',
    title: 'রবি ৩১০ মিনিট অফার',
    category: 'minute',
    operator: 'Robi',
    data: '0 MB',
    minutes: 310,
    sms: 0,
    validity: '30 Days',
    regularPrice: 260,
    salePrice: 235,
    cashback: 25,
    description: 'রবি ৩১০ মিনিট টকটাইম অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'robi-min-6',
    title: 'রবি ৩৬০ মিনিট অফার',
    category: 'minute',
    operator: 'Robi',
    data: '0 MB',
    minutes: 360,
    sms: 0,
    validity: '30 Days',
    regularPrice: 295,
    salePrice: 265,
    cashback: 30,
    description: 'রবি ৩৬০ মিনিট টকটাইম অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'robi-min-7',
    title: 'রবি ৪১০ মিনিট অফার',
    category: 'minute',
    operator: 'Robi',
    data: '0 MB',
    minutes: 410,
    sms: 0,
    validity: '30 Days',
    regularPrice: 335,
    salePrice: 300,
    cashback: 35,
    description: 'রবি ৪১০ মিনিট টকটাইম অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'robi-min-8',
    title: 'রবি ৫২৫ মিনিট অফার',
    category: 'minute',
    operator: 'Robi',
    data: '0 MB',
    minutes: 525,
    sms: 0,
    validity: '30 Days',
    regularPrice: 390,
    salePrice: 350,
    cashback: 40,
    isPopular: true,
    description: 'রবি ৫২৫ মিনিট টকটাইম স্পেশাল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'robi-min-9',
    title: 'রবি ৬২০ মিনিট অফার',
    category: 'minute',
    operator: 'Robi',
    data: '0 MB',
    minutes: 620,
    sms: 0,
    validity: '30 Days',
    regularPrice: 435,
    salePrice: 390,
    cashback: 45,
    isHot: true,
    description: 'রবি ৬২০ মিনিট টকটাইম স্পেশাল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'robi-min-10',
    title: 'রবি ৮০০ মিনিট অফার',
    category: 'minute',
    operator: 'Robi',
    data: '0 MB',
    minutes: 800,
    sms: 0,
    validity: '30 Days',
    regularPrice: 530,
    salePrice: 480,
    cashback: 50,
    isPopular: true,
    description: 'রবি ৮০০ মিনিট টকটাইম মেগা অফার, মেয়াদ ৩০ দিন।'
  },

  // ------------------ AIRTEL MINUTE PACKS ------------------
  {
    id: 'airtel-min-1',
    title: 'এয়ারটেল ১০০ মিনিট অফার',
    category: 'minute',
    operator: 'Airtel',
    data: '0 MB',
    minutes: 100,
    sms: 0,
    validity: '30 Days',
    regularPrice: 125,
    salePrice: 110,
    cashback: 15,
    description: 'এয়ারটেল ১০০ মিনিট টকটাইম অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-min-2',
    title: 'এয়ারটেল ২০০ মিনিট অফার',
    category: 'minute',
    operator: 'Airtel',
    data: '0 MB',
    minutes: 200,
    sms: 0,
    validity: '30 Days',
    regularPrice: 190,
    salePrice: 170,
    cashback: 20,
    description: 'এয়ারটেল ২০০ মিনিট টকটাইম অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-min-3',
    title: 'এয়ারটেল ৩০০ মিনিট অফার',
    category: 'minute',
    operator: 'Airtel',
    data: '0 MB',
    minutes: 300,
    sms: 0,
    validity: '30 Days',
    regularPrice: 235,
    salePrice: 210,
    cashback: 25,
    description: 'এয়ারটেল ৩০০ মিনিট টকটাইম অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-min-4',
    title: 'এয়ারটেল ৩৫০ মিনিট অফার',
    category: 'minute',
    operator: 'Airtel',
    data: '0 MB',
    minutes: 350,
    sms: 0,
    validity: '30 Days',
    regularPrice: 280,
    salePrice: 250,
    cashback: 30,
    description: 'এয়ারটেল ৩৫০ মিনিট টকটাইম অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-min-5',
    title: 'এয়ারটেল ৪০০ মিনিট অফার',
    category: 'minute',
    operator: 'Airtel',
    data: '0 MB',
    minutes: 400,
    sms: 0,
    validity: '30 Days',
    regularPrice: 315,
    salePrice: 285,
    cashback: 30,
    description: 'এয়ারটেল ৪০০ মিনিট টকটাইম অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-min-6',
    title: 'এয়ারটেল ৫০০ মিনিট অফার',
    category: 'minute',
    operator: 'Airtel',
    data: '0 MB',
    minutes: 500,
    sms: 0,
    validity: '30 Days',
    regularPrice: 365,
    salePrice: 330,
    cashback: 35,
    description: 'এয়ারটেল ৫০০ মিনিট টকটাইম অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-min-7',
    title: 'এয়ারটেল ৬০০ মিনিট অফার',
    category: 'minute',
    operator: 'Airtel',
    data: '0 MB',
    minutes: 600,
    sms: 0,
    validity: '30 Days',
    regularPrice: 445,
    salePrice: 400,
    cashback: 45,
    isPopular: true,
    description: 'এয়ারটেল ৬০০ মিনিট টকটাইম অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-min-8',
    title: 'এয়ারটেল ৮৪৫ মিনিট অফার',
    category: 'minute',
    operator: 'Airtel',
    data: '0 MB',
    minutes: 845,
    sms: 0,
    validity: '30 Days',
    regularPrice: 570,
    salePrice: 515,
    cashback: 55,
    isHot: true,
    description: 'এয়ারটেল ৮৪৫ মিনিট টকটাইম মেগা অফার, মেয়াদ ৩০ দিন।'
  },
  // ------------------ AIRTEL BUNDLE & INTERNET PACKS ------------------
  {
    id: 'airtel-bundle-1',
    title: 'এয়ারটেল ২৫ জিবি ইন্টারনেট',
    category: 'internet',
    operator: 'Airtel',
    data: '25 GB',
    minutes: 0,
    sms: 0,
    validity: '30 Days',
    regularPrice: 380,
    salePrice: 335,
    cashback: 20,
    description: 'এয়ারটেল ২৫ জিবি ৪জি স্পেশাল ইন্টারনেট প্যাক, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-2',
    title: 'এয়ারটেল ৩০ জিবি ইন্টারনেট',
    category: 'internet',
    operator: 'Airtel',
    data: '30 GB',
    minutes: 0,
    sms: 0,
    validity: '30 Days',
    regularPrice: 400,
    salePrice: 350,
    cashback: 25,
    description: 'এয়ারটেল ৩০ জিবি ৪জি স্পেশাল ইন্টারনেট প্যাক, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-3',
    title: 'এয়ারটেল ৩৫ জিবি ইন্টারনেট',
    category: 'internet',
    operator: 'Airtel',
    data: '35 GB',
    minutes: 0,
    sms: 0,
    validity: '30 Days',
    regularPrice: 490,
    salePrice: 430,
    cashback: 30,
    description: 'এয়ারটেল ৩৫ জিবি ৪জি স্পেশাল ইন্টারনেট প্যাক, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-4',
    title: 'এয়ারটেল ৪৫ জিবি ইন্টারনেট',
    category: 'internet',
    operator: 'Airtel',
    data: '45 GB',
    minutes: 0,
    sms: 0,
    validity: '30 Days',
    regularPrice: 520,
    salePrice: 460,
    cashback: 30,
    description: 'এয়ারটেল ৪৫ জিবি ৪জি স্পেশাল ইন্টারনেট প্যাক, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-5',
    title: 'এয়ারটেল ৫৫ জিবি ইন্টারনেট',
    category: 'internet',
    operator: 'Airtel',
    data: '55 GB',
    minutes: 0,
    sms: 0,
    validity: '30 Days',
    regularPrice: 600,
    salePrice: 535,
    cashback: 35,
    description: 'এয়ারটেল ৫৫ জিবি ৪জি মেগা ইন্টারনেট প্যাক, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-6',
    title: 'এয়ারটেল ৬০ জিবি ইন্টারনেট',
    category: 'internet',
    operator: 'Airtel',
    data: '60 GB',
    minutes: 0,
    sms: 0,
    validity: '30 Days',
    regularPrice: 620,
    salePrice: 545,
    cashback: 40,
    description: 'এয়ারটেল ৬০ জিবি ৪জি মেগা ইন্টারনেট প্যাক, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-7',
    title: 'এয়ারটেল ১০০ জিবি মেগা ইন্টারনেট',
    category: 'internet',
    operator: 'Airtel',
    data: '100 GB',
    minutes: 0,
    sms: 0,
    validity: '30 Days',
    regularPrice: 780,
    salePrice: 680,
    cashback: 50,
    isPopular: true,
    description: 'এয়ারটেল ১০০ জিবি ৪জি সুপার মেগা ধামাকা ইন্টারনেট প্যাক, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-8',
    title: 'এয়ারটেল ২০ জিবি + ২০০ মিনিট',
    category: 'combo',
    operator: 'Airtel',
    data: '20 GB',
    minutes: 200,
    sms: 0,
    validity: '30 Days',
    regularPrice: 400,
    salePrice: 350,
    cashback: 25,
    description: 'এয়ারটেল ২০ জিবি ইন্টারনেট + ২০০ মিনিট বান্ডেল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-9',
    title: 'এয়ারটেল ২০ জিবি + ৩০০ মিনিট',
    category: 'combo',
    operator: 'Airtel',
    data: '20 GB',
    minutes: 300,
    sms: 0,
    validity: '30 Days',
    regularPrice: 420,
    salePrice: 360,
    cashback: 25,
    description: 'এয়ারটেল ২০ জিবি ইন্টারনেট + ৩০০ মিনিট বান্ডেল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-10',
    title: 'এয়ারটেল ৩০ জিবি + ২০০ মিনিট',
    category: 'combo',
    operator: 'Airtel',
    data: '30 GB',
    minutes: 200,
    sms: 0,
    validity: '30 Days',
    regularPrice: 430,
    salePrice: 375,
    cashback: 25,
    description: 'এয়ারটেল ৩০ জিবি ইন্টারনেট + ২০০ মিনিট বান্ডেল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-11',
    title: 'এয়ারটেল ৩০ জিবি + ৩০০ মিনিট',
    category: 'combo',
    operator: 'Airtel',
    data: '30 GB',
    minutes: 300,
    sms: 0,
    validity: '30 Days',
    regularPrice: 460,
    salePrice: 400,
    cashback: 30,
    description: 'এয়ারটেল ৩০ জিবি ইন্টারনেট + ৩০০ মিনিট বান্ডেল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-12',
    title: 'এয়ারটেল ১০ জিবি + ৭০০ মিনিট',
    category: 'combo',
    operator: 'Airtel',
    data: '10 GB',
    minutes: 700,
    sms: 0,
    validity: '30 Days',
    regularPrice: 580,
    salePrice: 515,
    cashback: 35,
    description: 'এয়ারটেল ১০ জিবি ইন্টারনেট + ৭০০ মিনিট বান্ডেল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-13',
    title: 'এয়ারটেল ১২ জিবি + ৫০০ মিনিট',
    category: 'combo',
    operator: 'Airtel',
    data: '12 GB',
    minutes: 500,
    sms: 0,
    validity: '30 Days',
    regularPrice: 480,
    salePrice: 420,
    cashback: 30,
    description: 'এয়ারটেল ১২ জিবি ইন্টারনেট + ৫০০ মিনিট বান্ডেল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-14',
    title: 'এয়ারটেল ২০ জিবি + ৫০০ মিনিট',
    category: 'combo',
    operator: 'Airtel',
    data: '20 GB',
    minutes: 500,
    sms: 0,
    validity: '30 Days',
    regularPrice: 570,
    salePrice: 500,
    cashback: 35,
    description: 'এয়ারটেল ২০ জিবি ইন্টারনেট + ৫০০ মিনিট বান্ডেল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-15',
    title: 'এয়ারটেল ৪০ জিবি + ৮০০ মিনিট',
    category: 'combo',
    operator: 'Airtel',
    data: '40 GB',
    minutes: 800,
    sms: 0,
    validity: '30 Days',
    regularPrice: 700,
    salePrice: 620,
    cashback: 40,
    isHot: true,
    description: 'এয়ারটেল ৪০ জিবি ইন্টারনেট + ৮০০ মিনিট হট বান্ডেল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-16',
    title: 'এয়ারটেল ৫০ জিবি + ২০০ মিনিট',
    category: 'combo',
    operator: 'Airtel',
    data: '50 GB',
    minutes: 200,
    sms: 0,
    validity: '30 Days',
    regularPrice: 620,
    salePrice: 550,
    cashback: 35,
    description: 'এয়ারটেল ৫০ জিবি ইন্টারনেট + ২০০ মিনিট বান্ডেল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-17',
    title: 'এয়ারটেল ৫০ জিবি + ৩০০ মিনিট',
    category: 'combo',
    operator: 'Airtel',
    data: '50 GB',
    minutes: 300,
    sms: 0,
    validity: '30 Days',
    regularPrice: 640,
    salePrice: 560,
    cashback: 40,
    description: 'এয়ারটেল ৫০ জিবি ইন্টারনেট + ৩০০ মিনিট বান্ডেল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-18',
    title: 'এয়ারটেল ৬০ জিবি + ২০০ মিনিট',
    category: 'combo',
    operator: 'Airtel',
    data: '60 GB',
    minutes: 200,
    sms: 0,
    validity: '30 Days',
    regularPrice: 660,
    salePrice: 585,
    cashback: 40,
    description: 'এয়ারটেল ৬০ জিবি ইন্টারনেট + ২০০ মিনিট বান্ডেল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-19',
    title: 'এয়ারটেল ৬০ জিবি + ৩০০ মিনিট',
    category: 'combo',
    operator: 'Airtel',
    data: '60 GB',
    minutes: 300,
    sms: 0,
    validity: '30 Days',
    regularPrice: 680,
    salePrice: 600,
    cashback: 40,
    description: 'এয়ারটেল ৬০ জিবি ইন্টারনেট + ৩০০ মিনিট বান্ডেল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-20',
    title: 'এয়ারটেল ৬০ জিবি + ৫০০ মিনিট',
    category: 'combo',
    operator: 'Airtel',
    data: '60 GB',
    minutes: 500,
    sms: 0,
    validity: '30 Days',
    regularPrice: 710,
    salePrice: 625,
    cashback: 45,
    description: 'এয়ারটেল ৬০ জিবি ইন্টারনেট + ৫০০ মিনিট বান্ডেল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-21',
    title: 'এয়ারটেল ৮০ জিবি + ১০০ মিনিট',
    category: 'combo',
    operator: 'Airtel',
    data: '80 GB',
    minutes: 100,
    sms: 0,
    validity: '30 Days',
    regularPrice: 720,
    salePrice: 630,
    cashback: 45,
    description: 'এয়ারটেল ৮০ জিবি ইন্টারনেট + ১০০ মিনিট বান্ডেল অফার, মেয়াদ ৩০ দিন।'
  },
  {
    id: 'airtel-bundle-22',
    title: 'এয়ারটেল ৮০ জিবি + ৫০০ মিনিট',
    category: 'combo',
    operator: 'Airtel',
    data: '80 GB',
    minutes: 500,
    sms: 0,
    validity: '30 Days',
    regularPrice: 760,
    salePrice: 670,
    cashback: 50,
    isPopular: true,
    description: 'এয়ারটেল ৮০ জিবি ইন্টারনেট + ৫০০ মিনিট মেগা বান্ডেল অফার, মেয়াদ ৩০ দিন।'
  }
];
